"""Build data/offline-data.js from the dashboard CSVs.

Browsers block pages opened straight from disk (file://) from reading the CSVs,
so assets/data-loader.js reads this script copy of the same data instead.
Re-run it whenever data/*.csv changes:

    python dashboard/build_offline_data.py
"""
import csv
import json
from pathlib import Path

DATA = Path(__file__).resolve().parent / "data"


NUMERIC = {"p_fused", "xgb_contribution_pct", "gru_contribution_pct"}


def main():
    with open(DATA / "customer_scores_with_shap.csv", newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        cols = next(reader)
        numeric = [c in NUMERIC for c in cols]
        rows = [[round(float(v), 6) if num and v else v for v, num in zip(row, numeric)]
                for row in reader if row]

    # Monthly scores per customer, ordered by month_index (months start at 1).
    traj = {}
    with open(DATA / "customer_trajectories.csv", newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            traj.setdefault(row["customer_ID"], []).append(
                (int(row["month_index"]), round(float(row["risk_score"]), 4)))
    traj = {cid: [p for _, p in sorted(pts)] for cid, pts in traj.items()}

    payload = {"scores": {"cols": cols, "rows": rows}, "trajectories": traj}
    out = DATA / "offline-data.js"
    out.write_text(
        "// Generated by build_offline_data.py from data/*.csv - do not edit.\n"
        "window.FIRASA_OFFLINE = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"{out.name}: {len(rows)} customers, {len(traj)} trajectories, "
          f"{out.stat().st_size / 1e6:.1f} MB")


if __name__ == "__main__":
    main()
